name: Cypress E2E Tests

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "main"

  schedule:
    - cron: "*/5 * * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Install and run test
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6